function water_col_vars = extract_water_col(lat_lon, model_grid, ocean_data)
	%%% Extract 1-D water column model variables at specified horizontal grid point. %%%
    
    horiz_grid = model_grid.horizontal;
    water_col_vars.T = ocean_data.driving_vars.T(:,...
        horiz_grid.lat==lat_lon(1),horiz_grid.lon==lat_lon(2)); % in-situ temperature of seawater defined at grid cell center (degC)
    water_col_vars.O2 = ocean_data.driving_vars.O2(:,...
        horiz_grid.lat==lat_lon(1),horiz_grid.lon==lat_lon(2)); % dissolved oxygen defined at grid cell center (mol/m^3)
    water_col_vars.omegaC = ocean_data.driving_vars.omegaC(:,...
        horiz_grid.lat==lat_lon(1),horiz_grid.lon==lat_lon(2)); % saturation state of seawater with respect to calcite defined at grid cell center
    water_col_vars.omegaA = ocean_data.driving_vars.omegaA(:,...
        horiz_grid.lat==lat_lon(1),horiz_grid.lon==lat_lon(2)); % saturation state of seawater with respect to aragonite defined at grid cell center
    water_col_vars.rho_sw_wgrid = ocean_data.driving_vars.rho_w(:,...
        horiz_grid.lat==lat_lon(1),horiz_grid.lon==lat_lon(2)); % in-situ density of seawater defined on grid cell face (g/cm^3)
    water_col_vars.visc_wgrid = ocean_data.driving_vars.visc_w(:,...
        horiz_grid.lat==lat_lon(1),horiz_grid.lon==lat_lon(2)); % dynamic viscosity of seawater defined on grid cell face (g/cm/s)
    water_col_vars.epPOC = ocean_data.export.epPOC(...
        horiz_grid.lat==lat_lon(1),horiz_grid.lon==lat_lon(2)); % POC export flux at 100 m (mol C/m^2/s)
    water_col_vars.epCalc = ocean_data.export.epCalc(...
        horiz_grid.lat==lat_lon(1),horiz_grid.lon==lat_lon(2)); % calcite export flux at 100 m (mol C/m^2/s)
    water_col_vars.epArag = ocean_data.export.epArag(...
        horiz_grid.lat==lat_lon(1),horiz_grid.lon==lat_lon(2)); % aragonite export flux at 100 m (mol C/m^2/s)
    water_col_vars.epOpal = ocean_data.export.epOpal(...
        horiz_grid.lat==lat_lon(1),horiz_grid.lon==lat_lon(2)); % opal export flux at 100 m (mol Si/m^2/s)
end